// priority: 0

console.info('Starting recipe modification scripts...')

onEvent('item.registry', event => {
	// Register new items here
	// event.create('example_item').displayName('Example Item')
event.create('mark_miner').glow(true)
event.create('mark_farmer').glow(true)
event.create('mark_warrior').glow(true)
event.create('mark_archer').glow(true)
event.create('mark_wizard').glow(true)
event.create('mark_pirate').glow(true)
event.create('mark_thief').glow(true)
event.create('mark_huntsman').glow(true)
event.create('mark_healer').glow(true)
event.create('mark_pitfighter').glow(true)
event.create('mark_tamer').glow(true)

event.create('mark_spelunker').glow(true)
event.create('mark_rancher').glow(true)
event.create('mark_mercenary').glow(true) 
event.create('mark_arbalester').glow(true) 
event.create('mark_alchemist').glow(true) 
event.create('mark_corsair').glow(true)
event.create('mark_bandit').glow(true)
event.create('mark_tracker').glow(true) 
event.create('mark_spiritualist').glow(true) 
event.create('mark_fighter').glow(true)
event.create('mark_summoner').glow(true)

event.create('mark_cavemaster').glow(true)
event.create('mark_agrarian').glow(true)
event.create('mark_champion').glow(true)
event.create('mark_artillerist').glow(true)
event.create('mark_thaumaturge').glow(true)
event.create('mark_captain').glow(true)
event.create('mark_rogue').glow(true)
event.create('mark_pursuer').glow(true)
event.create('mark_shaman').glow(true)
event.create('mark_underdog').glow(true)
event.create('mark_beastmaster').glow(true)

event.create('arrow_down').
event.create('arrow_down_yellow')
event.create('arrow_up')
event.create('arrow_left')

event.create('copper_coin').tooltip('Acquired through quests')
event.create('iron_coin').tooltip('Acquired through quests')
event.create('gold_coin').tooltip('Acquired through quests')
event.create('diamond_coin').tooltip('Acquired through quests')
event.create('netherite_coin').tooltip('Acquired through quests')
event.create('monster_coin')
event.create('nether_coin').tooltip('Acquired through completing Nether chapter quests')

event.create('diamond_nugget')
event.create('emerald_nugget')
  
event.create('coin_01').tooltip('You can get these coins by selling valuable materials')
event.create('coin_02').tooltip('You can get these coins by selling valuable materials')
event.create('coin_03').tooltip('You can get these coins by selling valuable materials')
event.create('coin_04').tooltip('You can get these coins by selling valuable materials')
event.create('coin_05').tooltip('You can get these coins by selling valuable materials')
event.create('coin_06').tooltip('You can get these coins by selling valuable materials')

event.create('coin_q_1').tooltip('You can get these coins by doing quests')
event.create('coin_q_2').tooltip('You can get these coins by doing quests')


event.create('star').glow(true)
event.create('medal').glow(true)
event.create('heart')
event.create('heart-half')
event.create('caution')
event.create('chest')
event.create('chest2')
event.create('fire')
event.create('forbid')
event.create('help')
event.create('key')
event.create('key_01d')
event.create('lightning')
event.create('lock')
event.create('lock-2')
event.create('mark')
event.create('skull')
event.create('skull2')
event.create('skull3')
event.create('ace')
event.create('armour')
event.create('bleed')
event.create('book2')
event.create('book3')
event.create('book4')
event.create('book_02f')
event.create('book_04g')
event.create('campfire')
event.create('dice')
event.create('letter')
event.create('magnifier')
event.create('manuscript')
event.create('map')
event.create('mine')
event.create('ruby')
event.create('scroll')
event.create('scroll2')
event.create('scroll_01c')
event.create('magicscroll')
event.create('slash')
event.create('spellbook_01d')
event.create('spyglass')
event.create('levelup')
event.create('shield')
event.create('ring')
event.create('amulet')
event.create('rucksack')
event.create('bomb')
event.create('dodge')
event.create('scaling')

event.create('fox')
event.create('kruscle')
})
onEvent('block.registry', event => {
	// Register new blocks here
	// event.create('example_block').material('wood').hardness(1.0).displayName('Example Block')
})