// priority: 0

console.info('> JEI-Hide scripts starting...')

onEvent('jei.hide.items', event => {
	// Hide items in JEI here
	// event.hide('minecraft:cobblestone')
	
event.hide('simplefarming:rice_seeds')
event.hide('simplefarming:rice')		
		
event.hide('archers_paradox:phantasmal_arrow')

event.hide('productivebees:honeycomb_enderium')
event.hide('productivebees:honeycomb_electrum')
event.hide('productivebees:honeycomb_constantan')
event.hide('productivebees:honeycomb_cinnabar')
event.hide('productivebees:honeycomb_chocolate')
event.hide('productivebees:honeycomb_bronze')
event.hide('productivebees:honeycomb_brazen')
event.hide('productivebees:honeycomb_bismuth')
event.hide('productivebees:honeycomb_bauxite')
event.hide('productivebees:honeycomb_platinum')
event.hide('productivebees:honeycomb_pink_slimy')
event.hide('productivebees:honeycomb_osmium')
event.hide('productivebees:honeycomb_niter')
event.hide('productivebees:honeycomb_nickel')
event.hide('productivebees:honeycomb_menril')
event.hide('productivebees:honeycomb_lumium')
event.hide('productivebees:honeycomb_invar')
event.hide('productivebees:honeycomb_fluorite')
event.hide('productivebees:honeycomb_radioactive')
event.hide('productivebees:honeycomb_refined_glowstone')
event.hide('productivebees:honeycomb_refined_obsidian')
event.hide('productivebees:honeycomb_signalum')
event.hide('productivebees:honeycomb_silicon')
event.hide('productivebees:honeycomb_spacial')
event.hide('productivebees:honeycomb_steel')
event.hide('productivebees:honeycomb_tea')
event.hide('productivebees:honeycomb_titanium')
event.hide('productivebees:honeycomb_zinc')
event.hide('productivebees:honeycomb_ruby')
event.hide('productivebees:honeycomb_apatite')
event.hide('productivebees:honeycomb_spectrum')
event.hide('productivebees:honeycomb_cosmic_dust')
event.hide('productivebees:honeycomb_ichor_slimy')
event.hide('productivebees:honeycomb_ender_slimy')
event.hide('productivebees:honeycomb_sky_slimy')
event.hide('productivebees:honeycomb_tinkers_bronze')
event.hide('productivebees:honeycomb_soulsteel')
event.hide('productivebees:honeycomb_slimesteel')
event.hide('productivebees:honeycomb_rose_gold')
event.hide('productivebees:honeycomb_queens_slime')
event.hide('productivebees:honeycomb_pig_iron')
event.hide('productivebees:honeycomb_cobalt')
event.hide('productivebees:honeycomb_hepatizon')
event.hide('productivebees:honeycomb_manyullyn')
event.hide('productivebees:honeycomb_knightslime')
event.hide('productivebees:comb_enderium')
event.hide('productivebees:comb_electrum')
event.hide('productivebees:comb_constantan')
event.hide('productivebees:comb_cinnabar')
event.hide('productivebees:comb_chocolate')
event.hide('productivebees:comb_bronze')
event.hide('productivebees:comb_brazen')
event.hide('productivebees:comb_bismuth')
event.hide('productivebees:comb_bauxite')
event.hide('productivebees:comb_platinum')
event.hide('productivebees:comb_pink_slimy')
event.hide('productivebees:comb_osmium')
event.hide('productivebees:comb_niter')
event.hide('productivebees:comb_nickel')
event.hide('productivebees:comb_menril')
event.hide('productivebees:comb_lumium')
event.hide('productivebees:comb_invar')
event.hide('productivebees:comb_fluorite')
event.hide('productivebees:comb_radioactive')
event.hide('productivebees:comb_refined_glowstone')
event.hide('productivebees:comb_refined_obsidian')
event.hide('productivebees:comb_signalum')
event.hide('productivebees:comb_silicon')
event.hide('productivebees:comb_spacial')
event.hide('productivebees:comb_steel')
event.hide('productivebees:comb_tea')
event.hide('productivebees:comb_titanium')
event.hide('productivebees:comb_zinc')
event.hide('productivebees:comb_ruby')
event.hide('productivebees:comb_apatite')
event.hide('productivebees:comb_spectrum')
event.hide('productivebees:comb_cosmic_dust')
event.hide('productivebees:comb_ichor_slimy')
event.hide('productivebees:comb_ender_slimy')
event.hide('productivebees:comb_sky_slimy')
event.hide('productivebees:comb_tinkers_bronze')
event.hide('productivebees:comb_soulsteel')
event.hide('productivebees:comb_slimesteel')
event.hide('productivebees:comb_rose_gold')
event.hide('productivebees:comb_queens_slime')
event.hide('productivebees:comb_pig_iron')
event.hide('productivebees:comb_cobalt')
event.hide('productivebees:comb_hepatizon')
event.hide('productivebees:comb_manyullyn')
event.hide('productivebees:comb_knightslime')

event.hide('quark:magnet')
event.hide('quark:backpack')
event.hide('quark:ravager_hide')
event.hide('quark:bonded_ravager_hide')
event.hide('quark:pipe')
event.hide('quark:crate')
event.hide('quark:soul_compass')
event.hide('quark:matrix_enchanter')

event.hide('losttrinkets:rock_candy')
event.hide('losttrinkets:book_o_enchanting')
event.hide('losttrinkets:ash_gloves')
event.hide('losttrinkets:octopus_leg')
event.hide('losttrinkets:magical_feathers')

event.hide('pickletweaks:magnet')

event.hide('spartanshields:shield_botania_manasteel')
event.hide('spartanshields:shield_botania_terrasteel')
event.hide('spartanshields:shield_botania_elementium')
event.hide('spartanshields:shield_mekanism_osmium')
event.hide('spartanshields:shield_mekanism_lapis_lazuli')
event.hide('spartanshields:shield_mekanism_refined_glowstone')
event.hide('spartanshields:shield_mekanism_refined_obsidian')
event.hide('spartanshields:shield_mekanism_powered_basic')
event.hide('spartanshields:shield_mekanism_powered_advanced')
event.hide('spartanshields:shield_mekanism_powered_elite')
event.hide('spartanshields:shield_mekanism_powered_ultimate')

event.hide('mysticalworld:copper_spear')
event.hide('mysticalworld:lead_spear')
event.hide('mysticalworld:tin_spear')
event.hide('mysticalworld:stone_spear')
event.hide('mysticalworld:wood_spear')
event.hide('mysticalworld:diamond_spear')
event.hide('mysticalworld:gold_spear')
event.hide('mysticalworld:iron_spear')

event.hide('mysticalworld:cactus_knife')
event.hide('mysticalworld:lead_knife')
event.hide('mysticalworld:stone_knife')
event.hide('mysticalworld:wood_knife')
event.hide('mysticalworld:diamond_knife')
event.hide('mysticalworld:gold_knife')
event.hide('mysticalworld:iron_knife')
	
event.hide('mysticalworld:quicksilver_block')
event.hide('mysticalworld:quicksilver_sword')
event.hide('mysticalworld:silver_leggings')
event.hide('mysticalworld:silver_spear')
event.hide('mysticalworld:quicksilver_boots')
event.hide('mysticalworld:silver_pickaxe')
event.hide('mysticalworld:silver_wide_post')
event.hide('mysticalworld:silver_nugget')
event.hide('mysticalworld:quicksilver_spear')
event.hide('mysticalworld:quicksilver_nugget')
event.hide('mysticalworld:silver_sword')
event.hide('mysticalworld:quicksilver_wide_post')
event.hide('mysticalworld:silver_ingot')
event.hide('mysticalworld:quicksilver_chestplate')
event.hide('mysticalworld:silver_hoe')
event.hide('mysticalworld:silver_shovel')
event.hide('mysticalworld:quicksilver_helmet')
event.hide('mysticalworld:quicksilver_small_post')
event.hide('mysticalworld:silver_slab')
event.hide('mysticalworld:quicksilver_stairs')
event.hide('mysticalworld:quicksilver_wall')
event.hide('mysticalworld:silver_dust')
event.hide('mysticalworld:silver_axe')
event.hide('mysticalworld:silver_wall')
event.hide('mysticalworld:quicksilver_hoe')
event.hide('mysticalworld:quicksilver_pickaxe')
event.hide('mysticalworld:quicksilver_dust')
event.hide('mysticalworld:quicksilver_slab')
event.hide('mysticalworld:quicksilver_axe')
event.hide('mysticalworld:silver_stairs')
event.hide('mysticalworld:quicksilver_leggings')
event.hide('mysticalworld:silver_small_post')
event.hide('mysticalworld:silver_block')
event.hide('mysticalworld:silver_boots')
event.hide('mysticalworld:quicksilver_knife')
event.hide('mysticalworld:silver_helmet')
event.hide('mysticalworld:silver_chestplate')
event.hide('mysticalworld:quicksilver_ingot')
event.hide('mysticalworld:quicksilver_shovel')
event.hide('mysticalworld:quicksilver_ore')

event.hide('greekfantasy:wooden_spear')
event.hide('greekfantasy:stone_spear')
event.hide('greekfantasy:iron_spear')

event.hide('iceandfire:copper_sword')
event.hide('iceandfire:copper_shovel')
event.hide('iceandfire:copper_pickaxe')
event.hide('iceandfire:copper_axe')
event.hide('iceandfire:copper_hoe')
event.hide('iceandfire:silver_ore')
event.hide('iceandfire:sapphire_ore')
event.hide('iceandfire:copper_ore')
event.hide('iceandfire:armor_copper_metal_helmet')
event.hide('iceandfire:armor_copper_metal_chestplate')
event.hide('iceandfire:armor_copper_metal_leggings')
event.hide('iceandfire:armor_copper_metal_boots')

event.hide('eidolon:lead_ore')

event.hide('byg:ametrine_ore')
event.hide('byg:budding_ametrine_ore')
event.hide('byg:pendorite_ore')
	
event.hide('byg:raw_pendorite')
event.hide('byg:pendorite_ingot')
event.hide('byg:pendorite_scraps')
event.hide('byg:raw_pendorite_block')
event.hide('byg:pendorite_block')
event.hide('byg:pendorite_axe')
event.hide('byg:pendorite_pickaxe')
event.hide('byg:pendorite_sword')
event.hide('byg:pendorite_battleaxe')
event.hide('byg:pendorite_shovel')
event.hide('byg:pendorite_hoe')
event.hide('byg:pendorite_horse_armor')

event.hide('tropicraft:azurite_ore')
event.hide('tropicraft:eudialyte_ore')
event.hide('tropicraft:manganese_ore')
event.hide('tropicraft:shaka_ore')
event.hide('tropicraft:zircon_ore')

event.hide('spawnermod:spawner_key')

event.hide('apotheosis:iron_mining_arrow')
event.hide('apotheosis:diamond_mining_arrow')
event.hide('relics:magic_mirror')
})
