import crafttweaker.api.food.MCFood;

# fixing bad nutrients
<tag:items:forge:carbs>.add(
	<item:minecraft:bread>
);

# adding tags to non-food items because stews are stupid
<tag:items:forge:vegetables>.add(
	<item:minecraft:crimson_fungus>,
	<item:minecraft:suspicious_stew>,
	<item:twilightforest:mushgloom>
);

<tag:items:forge:fruits>.add(
	<item:twilightforest:torchberries>
);

# food tweaks, NU is calculated from (healing(int) + saturation(float) * 2)
# example The Forbidden Fruit had 0.0 NU, but Mixed Fruit from simplefarming has 12.8 NU
# therefore adding 4.2 NU (12.8 / 3 = 4.26666666667) for consistency
<item:enigmaticlegacy:forbidden_fruit>.food = new MCFood(1, 1.6);

# adding nutrients to items missing them
# vegetables
<tag:items:forge:vegetables>.add(
	<item:betterendforge:chorus_mushroom_raw>,
	<item:betterendforge:chorus_mushroom_cooked>,
	<item:mushroomquest:inkycaps>,
	<item:mushroomquest:chickenofthewoods>,
	<item:mushroomquest:micacaps>,
	<item:mushroomquest:indigomilkcap>,
	<item:mushroomquest:hexagonalpolypore>,
	<item:mushroomquest:swamprussula>,
	<item:mushroomquest:woolychanterelle>,
	<item:mushroomquest:beefsteakfungus>,
	<item:mushroomquest:pennybun>,
	<item:mushroomquest:destroyingangels>,
	<item:mushroomquest:henofthewoods>,
	<item:mushroomquest:lionsmane>,
	<item:mushroomquest:goldenchanterelle>,
	<item:mushroomquest:hornofplenty>,
	<item:mushroomquest:beechmushrooms>,
	<item:mushroomquest:columnstinkhorn>,
	<item:mushroomquest:pheasantback>,
	<item:mushroomquest:flyagaric>,
	<item:mushroomquest:woodears>,
	<item:mushroomquest:autumnskullcap>,
	<item:mushroomquest:birchpolypore>,
	<item:mushroomquest:falsemorel>,
	<item:mushroomquest:truemorel>,
	<item:mushroomquest:elfinsaddle>,
	<item:mushroomquest:velvetfoot>,
	<item:mushroomquest:apricotjelly>,
	<item:mushroomquest:pigsear>,
	<item:mushroomquest:rosyspikecap>,
	<item:mushroomquest:woodhedgehog>,
	<item:mushroomquest:honeymushroom>,
	<item:mushroomquest:sulfurtuft>,
	<item:mushroomquest:turkeytail>,
	<item:mushroomquest:tinderpolypore>,
	<item:mushroomquest:bluechanterelle>,
	<item:mushroomquest:saffronmilkcap>,
	<item:mushroomquest:chaga>,
	<item:mushroomquest:angelswing>,
	<item:mushroomquest:oldmanofthewoods>,
	<item:mushroomquest:deathcap>,
	<item:mushroomquest:kingbolete>,
	<item:mushroomquest:oystermushroom>,
	<item:mushroomquest:giantpolypore>,
	<item:mushroomquest:shiitake>,
	<item:mushroomquest:deadmansfingers>,
	<item:mushroomquest:kingtrumpet>,
	<item:mushroomquest:plantpotdapperling>,
	<item:mushroomquest:scarletcup>,
	<item:mushroomquest:clusteredcoral>,
	<item:mushroomquest:witchshat>,
	<item:mushroomquest:greenbrittlegill>,
	<item:mushroomquest:nameko>,
	<item:mushroomquest:earthstar>,
	<item:mushroomquest:latticemushroom>,
	<item:mushroomquest:bristledsawgill>,
	<item:mushroomquest:octopusstinkhorn>,
	<item:mushroomquest:devilsbolete>,
	<item:mushroomquest:wrinkledpeach>,
	<item:mushroomquest:caesarsmushroom>,
	<item:mushroomquest:laughinggym>,
	<item:mushroomquest:veiledlady>,
	<item:mushroomquest:lingzhimushroom>,
	<item:mushroomquest:chingulungulu>,
	<item:mushroomquest:caterpillarfungus>,
	<item:mushroomquest:meadowmushroom>,
	<item:mushroomquest:portobello>,
	<item:mushroomquest:fairyringmushroom>,
	<item:mushroomquest:horsemushroom>,
	<item:mushroomquest:panthercap>,
	<item:mushroomquest:brownrollrim>,
	<item:mushroomquest:parasolmushroom>,
	<item:mushroomquest:parrottoadstool>,
	<item:mushroomquest:crimsonwaxcap>,
	<item:mushroomquest:sandystiltball>,
	<item:mushroomquest:giantpuffball>,
	<item:mushroomquest:magicshrooms>,
	<item:mushroomquest:pinkwaxcap>,
	<item:mushroomquest:winecap>,
	<item:mushroomquest:yellowstainer>,
	<item:mushroomquest:commonbonnet>,
	<item:mushroomquest:bluingbolete>,
	<item:mushroomquest:devilsegg>,
	<item:mushroomquest:bleedingtoothfungus>,
	<item:mushroomquest:redcrackedbolete>,
	<item:mushroomquest:mossymazepolypore>,
	<item:mushroomquest:shortstemmedrussula>,
	<item:mushroomquest:chestnutmushroom>,
	<item:mushroomquest:birchbolete>,
	<item:mushroomquest:dyerspolypore>,
	<item:mushroomquest:slipperyjack>,
	<item:mushroomquest:agarikon>,
	<item:mushroomquest:scalypholiota>,
	<item:mushroomquest:blushingbracket>,
	<item:mushroomquest:purplefairyclub>,
	<item:mushroomquest:theblusher>,
	<item:mushroomquest:rufousmilkcap>,
	<item:mushroomquest:mushroomofthesun>,
	<item:mushroomquest:poisonfirecoral>,
	<item:mushroomquest:candycap>,
	<item:mushroomquest:lobstermushroom>,
	<item:mushroomquest:glowinggoo>,
	<item:mushroomquest:theprince>,
	<item:mushroomquest:manonhorseback>,
	<item:mushroomquest:darkscaledknight>,
	<item:mushroomquest:blueknight>,
	<item:mushroomquest:coraltoothfungus>,
	<item:mushroomquest:violetcort>,
	<item:mushroomquest:verdigrisagaric>,
	<item:mushroomquest:weepingwidow>,
	<item:mushroomquest:matsutake>,
	<item:mushroomquest:devilscigar>,
	<item:mushroomquest:scaberstalk>,
	<item:mushroomquest:woolymilkcap>,
	<item:mushroomquest:oakmazegill>,
	<item:mushroomquest:strawberrybracket>,
	<item:mushroomquest:hemlockvarnishshelf>,
	<item:mushroomquest:witchsbutter>,
	<item:mushroomquest:weepingconk>,
	<item:mushroomquest:snowfungus>,
	<item:mushroomquest:cauliflowerfungus>,
	<item:mushroomquest:candlesnuff>,
	<item:mushroomquest:goldenoyster>,
	<item:mushroomquest:cookeina>,
	<item:mushroomquest:cinnamonbracket>,
	<item:mushroomquest:redbandedpolypore>,
	<item:mushroomquest:baybolete>,
	<item:mushroomquest:werewerekokako>,
	<item:mushroomquest:bleedingfairyhelmet>,
	<item:mushroomquest:blacktruffle>,
	<item:mushroomquest:deadly_webcap>,
	<item:mushroomquest:red_tear_mushroom>,
	<item:mushroomquest:scarletina_bolete>,
	<item:mushroomquest:yellow_amanita>,
	<item:mushroomquest:grilled_portobello>,
	<item:byg:soul_shroom>,
	<item:byg:death_cap>,
	<item:byg:green_mushroom>,
	<item:byg:weeping_milkcap>,
	<item:byg:wood_blewit>,
	<item:byg:black_puff>,
	<item:blue_skies:winter_leaves>,
	<item:blue_skies:fiery_beans>,
	<item:blue_skies:cryo_root>,
	<item:eidolon:fungus_sprouts>,
	<item:eidolon:warped_sprouts>,
	<item:rats:assorted_vegetables>,
	<item:rats:contaminated_food>,
	<item:rats:confit_byaldi>,
	<item:rats:potato_kinishes>,
	<item:largemeals:omurice>,
	<item:feywild:mandrake>,
	<item:feywild:mandrake_potion>,
	<item:twilightdelight:thousand_plant_stew>,
	<item:twilightdelight:iron_lotus>,
	<item:twilightdelight:lily_chicken>,
	<item:undergarden:gloomgourd_pie>,
	<item:undergarden:bloody_stew>,
	<item:undergarden:inky_stew>,
	<item:undergarden:indigo_stew>,
	<item:undergarden:veiled_stew>,
	<item:abnormals_delight:venison_with_bamboo_shoots>
);

# protein
<tag:items:forge:protein>.add(
	<item:infernalexp:blindsight_tongue>,
	<item:infernalexp:spirit_eye>,
	<item:betterendforge:end_fish_raw>,
	<item:betterendforge:end_fish_cooked>,
	<item:mysticalworld:cooked_seeds>,
	<item:atum:emmer_bread>,
	<item:greekfantasy:gorgon_blood>,
	<item:greekfantasy:pomegranate_seeds>,
	<item:tropicraft:fresh_marlin>,
	<item:tropicraft:seared_marlin>,
	<item:tropicraft:raw_ray>,
	<item:tropicraft:cooked_ray>,
	<item:tropicraft:frog_leg>,
	<item:tropicraft:cooked_frog_leg>,
	<item:tropicraft:sea_urchin_roe>,
	<item:blue_skies:solnut>,
	<item:alexsmobs:shrimp_fried_rice>,
	<item:relics:infinity_ham>,
	<item:twilightforest:hydra_chop>,
	<item:largemeals:omurice>,
	<item:projectvibrantjourneys:clam>,
	<item:projectvibrantjourneys:cooked_clam>,
	<item:twilightdelight:lily_chicken>,
	<item:undergarden:underbeans>,
	<item:undergarden:roasted_underbeans>,
	<item:irregularchef:turkey_pot_pie_slice>,
	<item:irregularchef:birds_nest_soup>,
	<item:irregularchef:turtle_gallimaufry>,
	<item:artifacts:everlasting_beef>,
	<item:artifacts:eternal_steak>,
	<item:outer_end:stalker_meat>,
	<item:outer_end:cooked_stalker_meat>,
	<item:abnormals_delight:seared_venison>,
	<item:abnormals_delight:passionfruit_glazed_duck>,
	<item:abnormals_delight:dune_platter>,
	<item:abnormals_delight:duck_noodles>,
	<item:abnormals_delight:venison_with_bamboo_shoots>,
	<item:abnormals_delight:escargot>,
	<item:abnormals_delight:slabdish>,
	<item:fins:blu_wee>,
	<item:fins:pea_wee>,
	<item:fins:banded_redback_shrimp>,
	<item:fins:teal_arrowfish>,
	<item:fins:swamp_mucker>,
	<item:fins:flatback_sucker>,
	<item:fins:high_finned_blue>,
	<item:fins:ornate_bugfish>,
	<item:fins:wee_wee>,
	<item:fins:vibra_wee>,
	<item:fins:night_light_squid>,
	<item:fins:papa_wee>,
	<item:fins:cooked_banded_redback_shrimp>,
	<item:fins:bugmeat>,
	<item:fins:cooked_bugmeat>,
	<item:fins:raw_golden_river_ray_wing>,
	<item:fins:golden_river_ray_wing_fillet>,
	<item:fins:cooked_bull_crab_claw>,
	<item:fins:cooked_papa_wee>
);

# sweets
<tag:items:nourish:sweets>.add(
	<item:upgradednetherite_items:netherite_apple>,
	<item:upgradednetherite_items:enchanted_netherite_apple>,
	<item:upgradednetherite_items:gold_upgraded_netherite_apple>,
	<item:upgradednetherite_items:enchanted_gold_upgraded_netherite_apple>,
	<item:betterendforge:umbrella_cluster_juice>,
	<item:tombstone:lollipop>,
	<item:the_bumblezone:honey_crystal_shards>,
	<item:the_bumblezone:sugar_water_bottle>,
	<item:mowziesmobs:glowing_jelly>,
	<item:good_nights_sleep:candy>,
	<item:iceandfire:pixie_dust>,
	<item:iceandfire:ambrosia>,
	<item:iceandfire:cannoli>,
	<item:rats:treacle>,
	<item:twilightforest:experiment_115>,
	<item:buddycards:assorted_gummies>,
	<item:buddycards:buddybeans>,
	<item:buddycards:card.7.gummy1>,
	<item:buddycards:card.7.gummy2>,
	<item:buddycards:card.7.gummy3>,
	<item:buddycards:card.7.gummy4>,
	<item:buddycards:card.7.gummy5>,
	<item:buddycards:card.7.gummy6>,
	<item:largemeals:omurice>,
	<item:projectvibrantjourneys:coconut_milk>,
	<item:twilightdelight:aurora_ice_cream>,
	<item:productivebees:sugarbag_honeycomb>,
	<item:irregularchef:purple_cow_float>,
	<item:nethers_delight:magma_gelatin>,
	<item:buzzier_bees:sticky_honey_wand>,
	<item:abnormals_delight:cherry_cookie>,
	<item:abnormals_delight:maple_cookie>,
	<item:abnormals_delight:vanilla_cake_slice>,
	<item:abnormals_delight:chocolate_cake_slice>,
	<item:abnormals_delight:strawberry_cake_slice>,
	<item:abnormals_delight:banana_cake_slice>,
	<item:abnormals_delight:mint_cake_slice>,
	<item:abnormals_delight:adzuki_cake_slice>,
	<item:abnormals_delight:yucca_gateau_slice>
);

# fruits
<tag:items:forge:fruits>.add(
	<item:upgradednetherite_items:netherite_apple>,
	<item:upgradednetherite_items:enchanted_netherite_apple>,
	<item:upgradednetherite_items:gold_upgraded_netherite_apple>,
	<item:upgradednetherite_items:enchanted_gold_upgraded_netherite_apple>,
	<item:betterendforge:umbrella_cluster_juice>,
	<item:good_nights_sleep:rainbow_berries>,
	<item:atum:date>,
	<item:atum:golden_date>,
	<item:atum:golden_date_enchanted>,
	<item:byg:ether_bulbs>,
	<item:byg:holly_berries>,
	<item:byg:nightshade_berries>,
	<item:tropicraft:lemon>,
	<item:tropicraft:lime>,
	<item:tropicraft:grapefruit>,
	<item:tropicraft:orange>,
	<item:tropicraft:pineapple_cubes>,
	<item:tropicraft:coconut_chunk>,
	<item:blue_skies:cherry>,
	<item:blue_skies:scalefruit>,
	<item:blue_skies:pine_fruit>,
	<item:blue_skies:crescent_fruit>,
	<item:blue_skies:brewberry>,
	<item:blue_skies:pink_brewberry>,
	<item:blue_skies:black_brewberry>,
	<item:berry_nice:goldensweetberry>,
	<item:projectvibrantjourneys:juniper_berries>,
	<item:projectvibrantjourneys:cracked_coconut>,
	<item:ars_nouveau:mana_berry>,
	<item:enigmaticlegacy:forbidden_fruit>,
	<item:undergarden:droopvine_item>,
	<item:undergarden:blisterberry>,
	<item:undergarden:gloomgourd_pie>,
	<item:bayou_blues:gooseberries>,
	<item:bayou_blues:gooseberry_juice>,
	<item:endergetic:bolloom_fruit>,
	<item:nethers_delight:propelpearl>,
	<item:outer_end:azure_berries>,
	<item:farmersrespite:coffee_berries>
);

# carbs
<tag:items:forge:carbs>.add(
	<item:betterendforge:chorus_mushroom_raw>,
	<item:betterendforge:chorus_mushroom_cooked>,
	<item:alexsmobs:shrimp_fried_rice>,
	<item:iceandfire:cannoli>,
	<item:rats:potato_kinishes>,
	<item:twilightforest:maze_wafer>,
	<item:largemeals:omurice>,
	<item:brewevolution:full_dried_bread>,
	<item:brewevolution:dried_bread>,
	<item:irregularchef:traffic_jam_roll>,
	<item:abnormals_delight:duck_noodles>
);

# foods with no nutrients:
#
# farmersrespite:green_tea
# farmersrespite:yellow_tea
# farmersrespite:black_tea
# farmersrespite:coffee
# feywild:fey_dust
# undergarden:goo_ball
# brewevolution:full_mug_item
# brewevolution:kvass_mug
# brewevolution:mead_horn
# brewevolution:cider_glass_item
# brewevolution:calvados_glass_item
# brewevolution:vodka_glass_item
# brewevolution:liqueur_glass_item
# brewevolution:rum_glass_item
# irregularchef:dirt_cup